
package quoteClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuoteServerService", targetNamespace = "http://quoteServer/", wsdlLocation = "http://localhost:8888/quotes?wsdl")
public class QuoteServerService
    extends Service
{

    private final static URL QUOTESERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUOTESERVERSERVICE_EXCEPTION;
    private final static QName QUOTESERVERSERVICE_QNAME = new QName("http://quoteServer/", "QuoteServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/quotes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUOTESERVERSERVICE_WSDL_LOCATION = url;
        QUOTESERVERSERVICE_EXCEPTION = e;
    }

    public QuoteServerService() {
        super(__getWsdlLocation(), QUOTESERVERSERVICE_QNAME);
    }

    public QuoteServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUOTESERVERSERVICE_QNAME, features);
    }

    public QuoteServerService(URL wsdlLocation) {
        super(wsdlLocation, QUOTESERVERSERVICE_QNAME);
    }

    public QuoteServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUOTESERVERSERVICE_QNAME, features);
    }

    public QuoteServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuoteServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuoteServer
     */
    @WebEndpoint(name = "QuoteServerPort")
    public QuoteServer getQuoteServerPort() {
        return super.getPort(new QName("http://quoteServer/", "QuoteServerPort"), QuoteServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteServer
     */
    @WebEndpoint(name = "QuoteServerPort")
    public QuoteServer getQuoteServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://quoteServer/", "QuoteServerPort"), QuoteServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUOTESERVERSERVICE_EXCEPTION!= null) {
            throw QUOTESERVERSERVICE_EXCEPTION;
        }
        return QUOTESERVERSERVICE_WSDL_LOCATION;
    }

}
