
package quoteClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuoteService", targetNamespace = "http://quoteServer/", wsdlLocation = "http://localhost:8080/quotes?wsdl")
public class QuoteService
    extends Service
{

    private final static URL QUOTESERVICE_WSDL_LOCATION;
    private final static WebServiceException QUOTESERVICE_EXCEPTION;
    private final static QName QUOTESERVICE_QNAME = new QName("http://quoteServer/", "QuoteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/quotes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUOTESERVICE_WSDL_LOCATION = url;
        QUOTESERVICE_EXCEPTION = e;
    }

    public QuoteService() {
        super(__getWsdlLocation(), QUOTESERVICE_QNAME);
    }

    public QuoteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUOTESERVICE_QNAME, features);
    }

    public QuoteService(URL wsdlLocation) {
        super(wsdlLocation, QUOTESERVICE_QNAME);
    }

    public QuoteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUOTESERVICE_QNAME, features);
    }

    public QuoteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuoteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Quote
     */
    @WebEndpoint(name = "QuotePort")
    public Quote getQuotePort() {
        return super.getPort(new QName("http://quoteServer/", "QuotePort"), Quote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Quote
     */
    @WebEndpoint(name = "QuotePort")
    public Quote getQuotePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://quoteServer/", "QuotePort"), Quote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUOTESERVICE_EXCEPTION!= null) {
            throw QUOTESERVICE_EXCEPTION;
        }
        return QUOTESERVICE_WSDL_LOCATION;
    }

}
