
package quoteClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Quote", targetNamespace = "http://quoteServer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Quote {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuote", targetNamespace = "http://quoteServer/", className = "quoteClient.src.main.java.quoteClient.GetQuote")
    @ResponseWrapper(localName = "getQuoteResponse", targetNamespace = "http://quoteServer/", className = "quoteClient.src.main.java.quoteClient.GetQuoteResponse")
    @Action(input = "http://quoteServer/Quote/getQuoteRequest", output = "http://quoteServer/Quote/getQuoteResponse")
    public String getQuote();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addQuote", targetNamespace = "http://quoteServer/", className = "quoteClient.src.main.java.quoteClient.AddQuote")
    @ResponseWrapper(localName = "addQuoteResponse", targetNamespace = "http://quoteServer/", className = "quoteClient.src.main.java.quoteClient.AddQuoteResponse")
    @Action(input = "http://quoteServer/Quote/addQuoteRequest", output = "http://quoteServer/Quote/addQuoteResponse")
    public void addQuote(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
